import re
f = open("ptbr/all.json", encoding="utf-8")
todos = f.read()
f.close()
noite1 = ["Dusk",
		"Fabled",
		"Lord of Typhon",
		"Kazali",
		"Apprentice",
		"Barista",
		"Bureaucrat",
		"Thief",
		"Boffin",
		"Philosopher",
		"Alchemist",
		"Poppy Grower",
		"Yaggababble",
		"Magician",
		"MINION",
		"Snitch",
		"Lunatic",
		"Summoner",
		"DEMON",
		"King",
		"Sailor",
		"Marionette",
		"Engineer",
		"Preacher",
		"Lil Monsta",
		"Lleech",
		"Xaan",
		"Poisoner",
		"Widow",
		"Courtier",
		"Wizard",
		"Snake Charmer",
		"Godfather",
		"Organ Grinder",
		"Devils Advocate",
		"Evil Twin",
		"Witch",
		"Cerenovus",
		"Fearmonger",
		"Harpy",
		"Mezepheles",
		"Pukka",
		"Pixie",		
		"Huntsman",
		"Damsel",
		"Amnesiac",
		"Washerwoman",
		"Librarian",
		"Investigator",
		"Chef",
		"Empath",
		"Fortune Teller",
		"Butler",
		"Grandmother",
		"Clockmaker",
		"Dreamer",
		"Seamstress",
		"Steward",
		"Knight",
		"Noble",
		"Balloonist",
		"Shugenja",
		"Village Idiot",
		"Bounty Hunter",
		"Nightwatchman",
		"Cult Leader",
		"Spy",
		"Ogre",
		"High Priestess",
		"General",
		"Chambermaid",
		"Mathematician",
		"DAWN",
		"Leviathan",
		"Vizier"]
noites = ["Dusk",
		"Fabled",
		"Barista",
		"Bone Collector",
		"Bureaucrat",
		"Harlot",
		"Thief",
		"Philosopher",		
		"Poppy Grower",
		"Sailor",
		"Engineer",
		"Preacher",
		"Xaan",
		"Poisoner",
		"Courtier",
		"Innkeeper",
		"Wizard",
		"Gambler",
		"Acrobat",
		"Snake Charmer",
		"Monk",
		"Organ Grinder",
		"Devils Advocate",
		"Witch",
		"Cerenovus",
		"Pit-Hag",
		"Fearmonger",
		"Harpy",
		"Mezepheles",
		"Scarlet Woman",
		"Summoner",
		"Lunatic",
		"Exorcist",
		"Lycanthrope",
		"Legion",
		"Imp",
		"Zombuul",
		"Pukka",
		"Shabaloth",
		"Po",
		"Fang Gu",
		"No Dashii",
		"Vortox",
		"Lord of Typhon",
		"Vigormortis",
		"Ojo",
		"Al-Hadikhia",
		"Lleech",
		"Lil Monsta",
		"Yaggababble",
		"Kazali",
		"Assassin",
		"Godfather",
		"Gossip",
		"Hatter",
		"Barber",
		"Sweetheart",		
		"Sage",
		"Banshee",
		"Professor",
		"Choirboy",
		"Huntsman",
		"Damsel",		
		"Amnesiac",
		"Farmer",
		"Tinker",
		"Moonchild",
		"Grandmother",
		"Ravenkeeper",
		"Empath",
		"Fortune Teller",
		"Undertaker",
		"Dreamer",
		"Flowergirl",
		"Town Crier",
		"Oracle",
		"Seamstress",
		"Juggler",
		"Balloonist",
		"King",
		"Village Idiot",
		"Bounty Hunter",
		"Nightwatchman",
		"Cult Leader",
		"Butler",
		"Spy",
		"High Priestess",
		"General",
		"Chambermaid",
		"Mathematician",
		"DAWN",
		"Leviathan"]
i = 0
for role in noite1:
	idrole = todos.find('{\n    "id": "'+ role.lower().replace(" ", "")+"_br")
	idnoite1 = todos.find('"firstNight": ', idrole)
	if idrole != -1:
		novonumero = str(i)
		if i < 10: novonumero = " "+novonumero
		todos = todos[:idnoite1+14] + novonumero + todos[idnoite1+16:]
	i += 1
i = 0
for role in noites:
	idrole = todos.find('{\n    "id": "'+ role.lower().replace(" ", "")+"_br")
	idnoites = todos.find('"otherNight": ', idrole)
	if idrole != -1:
		novonumero = str(i)
		if i < 10: novonumero = " "+novonumero
		todos = todos[:idnoites+14] + novonumero + todos[idnoites+16:]
	i += 1
f = open("ptbr/all.json", "w", encoding="utf-8")
f.write(todos)
f.close()


